### ISSUE TITLE
L2: Forbid `unwrap`s

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1266]
Add the following clippy lint to all `Cargo.toml` files in the `l2` crate:

```toml
[lints.clippy]
unwrap_used = "deny"
```

and remove the `unwrap`s of the module.
