### ISSUE TITLE
L2: Forbid `expect`s

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1267]
Add the following clippy lint to all `Cargo.toml` files in the `l2` crate:

```toml
[lints.clippy]
expect = "deny"
```

and remove the `expect`s of the module.
