### ISSUE TITLE
L2: Remove `as` conversions

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1268]
Add the following clippy lint to all `Cargo.toml` files in the `l2` crate:

```toml
[lints.clippy]
as_conversions = "deny"
unnecessary_cast = "warn"
```

and remove the conversions of the module if necessary.
