### ISSUE TITLE
L2: Forbid indexing slicing

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1270]
Add the following clippy lint to all `Cargo.toml` files in the `l2` crate:

```toml
[lints.clippy]
indexing_slicing = "deny"
```

and make the indexing safe where necessary.
